spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bfq_business?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8088

mybatis:
  typeAliasesPackage: com.hzw.pay.entity
  configuration:
    map-underscore-to-camel-case: true