aliyun:
  oss:
    endPoint: http://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4FmZfJdLhMr5BHz5ecFZ
    accessKeySecret: D6Qs7YXpy6IpYFKnzqD6qcwnZY81gV
    bucketName: hzw-bucket
    fileFolder: myfiles
    deletedFolder: deletedfiles